# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.box_check_update = false
  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network :forwarded_port, guest: 22, host: 12222, id: "ssh"
  #config.vm.network "public_network"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096
    vb.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL

    # Prepare Yocto environment.
    sudo apt-get update
    sudo apt-get install -y gawk wget git-core diffstat unzip texinfo gcc-multilib \
    build-essential chrpath socat cpio python python3 python3-pip python3-pexpect \
    xz-utils debianutils iputils-ping libsdl1.2-dev xterm

    # static code analisis tool
    sudo apt install -y splint cppcheck
    sudo apt install -y nginx
    sudo wget https://bootstrap.pypa.io/pip/2.7/get-pip.py -O get-pip.py
    sudo python get-pip.py
    sudo pip install pygments

  SHELL

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    # Yocto build
    mkdir ~/yocto
    cd ~/yocto
    git clone git://git.yoctoproject.org/poky -b rocko
    cd poky

    git clone git://git.openembedded.org/meta-openembedded -b rocko

    # add raspberrypi BSP
    git clone git://git.yoctoproject.org/meta-raspberrypi -b rocko

    # swupdate
    git clone https://github.com/sbabic/meta-swupdate.git -b rocko
    git clone https://github.com/sbabic/meta-swupdate-boards.git -b rocko

    source oe-init-build-env build
    bitbake-layers add-layer ../meta-openembedded/meta-oe/
    bitbake-layers add-layer ../meta-openembedded/meta-python/
    bitbake-layers add-layer ../meta-openembedded/meta-multimedia/
    bitbake-layers add-layer ../meta-openembedded/meta-networking/
    bitbake-layers add-layer ../meta-raspberrypi/
    bitbake-layers add-layer ../meta-swupdate/
    bitbake-layers add-layer ../meta-swupdate-boards/

    MACHINE=raspberrypi3 bitbake update-image

  SHELL

end


